### ISSUE TITLE
Inotify watch limit reached during sync operation

### ISSUE THREAD

**Issue by iwannet** [FilenCloudDienste/filen-cli#105]
When using `filen-cli` to sync files, the following error occurs:

```
filen-cli sync /local:lb:/cloud --continuous
Syncing /local to /cloud (localBackup)...
node:internal/process/promises:288
           triggerUncaughtException(err, true /* fromPromise */);
           ^
[Error: inotify_add_watch on '/a-local-dir' failed: No space left on device]
Node.js v18.19.1
```

This error suggests that the system has reached its limit for inotify watches, not that it has run out of disk space.

## Environment

- Operating System: Debian 12 Bookworm 
- Node.js version: v18.19.1
- filen-cli version: v0.0.8

## Proposed Solution

Consider implementing one of the following solutions in filen-cli:

1. Automatically increase the inotify watch limit if possible.
2. Provide a clear error message suggesting how to increase the limit.
3. Implement a fallback mechanism that doesn't rely on inotify when the limit is reached.

As a temporary workaround, users can increase the inotify watch limit by running:

```
sudo sysctl fs.inotify.max_user_watches=524288
```

To make this change permanent, add the following line to /etc/sysctl.conf:

```
fs.inotify.max_user_watches=524288
```

Then run:

```
sudo sysctl -p
```

Thanks for your amazing product !

**Comment by JupiterPi** [comment]
Thank you for your feedback! This issue has been fixed [here](https://github.com/FilenCloudDienste/filen-sync/commit/b6c814f990907e925fb14409ce9a285438d14b59).
