### ISSUE TITLE
[Bug] Version 0.0.9, the sync command does not delete the files.

### ISSUE THREAD

**Issue by iz2bkt** [FilenCloudDienste/filen-cli#115]
**Describe the bug**
Version 0.0.9, when using the 'filen sync' command in 'localToCloud' mode, does not delete files on Filen when they are deleted locally. Version 0.0.8 performed this function correctly.

**To Reproduce**
1. I sync the /home/ubuntu/documents folder with /documents in Filen cloud
2. I delete the file prova1.doc from /home/ubuntu/documents
3. Now I re-sync the /home/ubuntu/documents folder with /documents in Filen cloud
4. The file prova1.doc was not deleted from the /documents folder in Filen cloud.
5. The command: filen sync /home/ubuntu/filen/syncFilen.json
6. The syncFilen.json: 
7. [
    {
        "local": "/home/ubuntu/documents/",
        "remote": "/documents",
        "syncMode": "localToCloud",
        "alias": "syncDocuments",
        "disableLocalTrash": true
   }
]

**Expected behavior**
As in version 0.0.8, files deleted locally should also be deleted in the Filen cloud.

**Screenshots**

**System (please complete the following information):**
- **0.0.9**
- OS: Ubuntu 24.04.1 LTS
- hardware configuration ARM, 16GB RAM

**Additional context**

**Comment by Dwynr** [comment]
So after a lot of digging and trying to reproduce this issue we found out what happened:

The underlying filen-sync package is still a work in progress and not officially released yet (just like the CLI). We updated the way current and previous metadata + state is saved locally in the sync package (such as tree changes etc.). This caused your CLI sync to think it was "new" without any previous saved state, hence not picking up your local deletions correctly.

It is advised to not use the CLI for any critical data right now, as it is still in beta and not officially released.
