### ISSUE TITLE
[Feature Request] Disable update check

### ISSUE THREAD

**Issue by kooWZ** [FilenCloudDienste/filen-cli#125]
I am using this cli in a bash file which will be automatically executed. 
However, when a new version is available, the program just hangs at `Update from ${currentVersion} to ${publishedVersion}? [y/N]` and waiting for input. 
Could you add a commandline argument like `--skip-update` to allow the program to skip update check?

**Comment by NaolShow** [comment]
I was about to open an issue for that too ahah

Would be perfect, since I'm using the CLI to automatically backup some data to Filen.

**Comment by JupiterPi** [comment]
Thank you for the feedback, we'll add that.

**Comment by JupiterPi** [comment]
This is now availabe in [v0.0.11](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.11).
