### ISSUE TITLE
[Bug] Mount broken on Linux

### ISSUE THREAD

**Issue by Ethorbit** [FilenCloudDienste/filen-cli#146]
**Describe the bug**
Trying to mount on a non-Debian distro (and possibly any distro ?) won't work.

This has been tested with filen-cli v0.0.12 on both Alpine Linux v3.20 (same one the [filen/cli docker image](https://hub.docker.com/repository/docker/filen/cli) is based on) and NixOS 24.05.

1. `mkdir "$HOME/mnt"`
2. `filen mount "$HOME/mnt"`

> FUSE 3 is needed in Linux for network drive mounting. FUSE 3 could not be found.

Huh?
`command -v fusermount3 && echo "FUSE 3 is in fact installed"`

> /run/wrappers/bin/fusermount3
> FUSE 3 is in fact installed

The reason it thinks FUSE 3 is not installed when it is, is because filen-network-drive checks with `dpkg` (which **only exists in Debian!**)
```
		const dpkg = await execCommand(
			// eslint-disable-next-line quotes
			'dpkg -l | grep -E "^ii\\s+fuse3\\s|^ii\\s+libfuse3\\s"'
		)

		if (dpkg.includes("fuse3")) {
			return true
		}
```

If we bypass it with bash:

`dpkg() { echo "ii fuse3 ii libfuse3"; } && export -f dpkg`

And try mounting again:

1. `mkdir "$HOME/mnt"`
2. `filen mount "$HOME/mnt"`

we get this new error:

> Error trying to execute mount command: Cannot mount to a directory outside of your home directory.
> Error: Cannot mount to a directory outside of your home directory.

but we are mounting inside the home directory. What gives?

**Expected behavior**
Actually mounting

**Comment by Dwynr** [comment]
Thanks for reporting, should be fixed via https://github.com/FilenCloudDienste/filen-network-drive/commit/14c5e372a8ca5dcf293123ea8a31f58acefed662

Will be included in the next CLI release. For mounting please only use absolute paths without any variables.
