### ISSUE TITLE
[Bug] Webdav server not compatible with Kopia - Blob timestamp error

### ISSUE THREAD

**Issue by panomitrius** [FilenCloudDienste/filen-cli#151]
**Describe the bug**
The local Filen CLI webdav server isn't compatible with Kopia.

**To Reproduce**
1. Invoke Filen CLI with arguments: filen_webdav filen webdav --w-port 9089 --w-user user --w-password password **[Works fine]**
2. Set up a Kopia repository: kopia repository create webdav --url http://localhost:9089/Backups/Kopia-Flourish --webdav-username user --webdav-password password **[Works fine]**
3. Validate Kopia repository: kopia repository validate-provider: generates this:

```
kopia repository validate-provider
Opening 4 equivalent storage connections...
Validating storage capacity and usage
Validating blob list responses
Validating non-existent blob responses
Writing blob (5000000 bytes)
Validating conditional creates...
Validating list responses...
Validating partial reads...
Validating full reads...
Validating metadata...
Cleaning up temporary data...
ERROR provider validation error: newly-written blob has a timestamp very different from local clock: 2024-10-12 11:26:15 +0000 GMT, expected 2024-10-12 11:26:17.562434587 +0200 CEST. Max difference allowed is 3m0s
```

**Expected behavior**
Validation works.

**Logs/Screenshots**
Filen CLI doesn't output anything.

**System (please complete the following information):**
- **Filen CLI version:** v0.0.12
- OS: Ubuntu 22.04.4 LTS

----

Is this a time zone issue?

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-webdav/commit/7e3998aa931a25e9d9ad286900338879865a6302
