### ISSUE TITLE
[Bug] Mount not working on linux

### ISSUE THREAD

**Issue by JunaidQrysh** [FilenCloudDienste/filen-cli#158]
**Describe the bug**
I am using Arch Linux and filen-cli-v0.0.13-linux-x64 and fuse3 is installed,
the follwing command produces an error .
`./filen mount "/home/qrysh/filen"`

Mounting network drive for junaidqrysh@gmail.com at X:
Error trying to execute mount command: Cannot mount to a directory outside of your home directory.
Error: Cannot mount to a directory outside of your home directory.
    at NetworkDrive.start (/snapshot/filen-cli/dist/bundle.js)
    at async DriveMountingInterface.invoke (/snapshot/filen-cli/dist/bundle.js)
    at async /snapshot/filen-cli/dist/bundle.js

**Comment by JupiterPi** [comment]
There was a bug with the command parsing (as you can see, it tried to mount at "X:", not where you specified). 
It should be fixed in [v0.0.14](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.14).

**Comment by JunaidQrysh** [comment]
@JupiterPi Now mount seemingly works but the mount folder is empty i have tried in both file manager and another terminal

`filen mount /home/qrysh/jmount/`
Mounting network drive for junaidqrysh@gmail.com at /home/qrysh/jmount/
\> ls
\>

**Comment by JunaidQrysh** [comment]
Here is  my test folder on root directory which should be present in mounted location.
`filen`
/ > ls
test
/ >

**Comment by JupiterPi** [comment]
Please describe your problem in a new Issue using the issue template
