### ISSUE TITLE
How to run in macos without getting killed?

### ISSUE THREAD

**Issue by panomitrius** [FilenCloudDienste/filen-cli#161]
How do I run this in macos terminal without it just getting killed? I'm trying the arm64 version on a macbook m1. I've tried with both sudo and regular user. And I've allowed it in security settings...

**Comment by JupiterPi** [comment]
This is an error with the NodeJS to executable binary compilation, which affects both Windows and MacOS on ARM processors. For now, please resort to emulating the x64 executable. We will fix this issue in the future.

**Comment by JupiterPi** [comment]
(macOS arm64 and x64 builds are available from `v0.0.31` and newer)
