### ISSUE TITLE
[Feature Request] (bug?)

### ISSUE THREAD

**Issue by halictuz** [FilenCloudDienste/filen-cli#192]
So, first of all, good work on the latest versions for Web, Desktop and the CLI versions. I like it so far. 

(not sure if its a bug or just a feature thats not implemented yet)

Am I missing something, or how would I start a S3 server or mount a Network Drive with the Filen on my headless server (raspberry pi for example) but running in background?

It seems like that Filen wants to run in the foreground otherwise it cancels everything and nothing works. Once I close the terminal the server/mounting stops working.

Thanks for the new versions
greetings

**Comment by Dwynr** [comment]
Daemon mode is not yet implemented. You can use packages like `screen` to start the client and then detach from the screen session. This will keep it open in the background.
