### ISSUE TITLE
[Bug] login fails when starting webdav with credentials via arguments

### ISSUE THREAD

**Issue by bhopmann** [FilenCloudDienste/filen-cli#193]
**Describe the bug**
filen-cli throws an error when starting webdav with credentials via arguments (login fails)

**To Reproduce**
1. run filen-cli like this: `filen-cli -v --email myemail --password mypassword --skip-update webdav --w-user "admin" --w-password "admin" --w-https --w-hostname 192.168.3.1 --w-port 8453`
2. see thrown error

**Expected behavior**
login successful and start webdav server

**Logs**

```
Filen CLI v0.0.18
Update check skipped
Logging in as myemail (using arguments)
Error trying to login: Not authenticated, please call login() first
Error: Not authenticated, please call login() first
    at FilenSDK.crypto (/snapshot/filen-cli/dist/bundle.js)
    at FilenSDK.getWorker (/snapshot/filen-cli/dist/bundle.js)
    at APIClient.post (/snapshot/filen-cli/dist/bundle.js)
    at send (/snapshot/filen-cli/dist/bundle.js)
    at send (/snapshot/filen-cli/dist/bundle.js)
    at async send (/snapshot/filen-cli/dist/bundle.js)
    at async send (/snapshot/filen-cli/dist/bundle.js)
    at async send (/snapshot/filen-cli/dist/bundle.js)
    at async send (/snapshot/filen-cli/dist/bundle.js)
    at async send (/snapshot/filen-cli/dist/bundle.js)
```

**System (please complete the following information):**
- **Filen CLI version:** v0.0.18
- OS: Raspberry Pi 5 (aarch64) with Raspberry OS

**Comment by bhopmann** [comment]
I investigated a little bit more: Are there any problems with parsing special characters in passwords?

**Comment by N1v0k** [comment]
+ 1

filen-cli login seems broken, (not only webdav), tested on windows and linux.
Changed pw to be alpha-numeric only - didn't work
disabled 2Fa - did not resolve the issue

Same error + stacktrace as above!

**Comment by marcbres** [comment]
I'm using the cli on a script to upload a file, and it also fails to me with the
`Error trying to login: Not authenticated, please call login() first`

Downgrading to v0.0.17 works fine, so seems that something about login is broken on the v0.0.18

**Comment by Dwynr** [comment]
Thanks for reporting, I will take a look as soon as I can.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-cli/commit/86c320ef604204f19fd9b40ae4dd8d1fcbed9d3d
