### ISSUE TITLE
[Feature Request] Run syncs in background and at boot

### ISSUE THREAD

**Issue by nthpyrodev** [FilenCloudDienste/filen-cli#195]
I want to be able to make Filen CLI run in the background, without having to have a terminal session open for it. While using screen works as a temporary fix, I see background sync/usage as essential functionality, and am surprised that Filen CLI doesn't already have this functionality.
An extension of background sync is to have the sync run at boot, if chosen by the user, meaning that it doesn't have to be started every time I decide to restart my server.

**Comment by Dwynr** [comment]
You can create a `systemd` service for that, no need for us to put that directly into the CLI, as it would be overcomplicated.
