### ISSUE TITLE
[Bug] Login fails when login info is requested by cli

### ISSUE THREAD

**Issue by sjiawjbssj** [FilenCloudDienste/filen-cli#196]
**Describe the bug**
When logging in using filen --email --password --two-factor-code everything works fine but when the cli asks my credentials (like when typing filen ls without logging in prior) I get an error saying "Invalid credentials!". It might be a problem with the password length because the password isn't fully displayed and the "p" from the word "password:" disappears. After tapping backspace the rest of the password is shown but logging in is still not possible.

**To Reproduce**
1. Set an account password with over 120 characters
2. run e.g. filen ls
3. try to login

**System (please complete the following information):**
- **Filen CLI version:** v0.0.17
- OS: Windows 10
- VPN used

**Comment by JupiterPi** [comment]
Thanks for reporting! Unfortunately, I could not really reproduce the invalid credentials with a password >120 characters. However, I made some changes to the input method (to address the weird behaviour when pressing backspace), maybe your issue is fixed, too, in [v0.0.21](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.21)?

**Comment by brokosz** [comment]
similar error here - the CLI doesn't not prompt for 2FA when invoked without the options and fails authN. 
```bash
bash-5.2$ filen
Please enter your Filen credentials:
Email: 
Password: 
Error trying to login: APIError: Wrong Two Factor Authentication code.
APIError: Wrong Two Factor Authentication code.
    at send (/snapshot/filen-cli/dist/bundle.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async APIClient.request (/snapshot/filen-cli/dist/bundle.js)
    at async Login.fetch (/snapshot/filen-cli/dist/bundle.js)
    at async FilenSDK.login (/snapshot/filen-cli/dist/bundle.js)
    at async Authentication.authenticate (/snapshot/filen-cli/dist/bundle.js)
    at async /snapshot/filen-cli/dist/bundle.js
    ```

**Comment by brokosz** [comment]
@sjiawjbssj I created a new issue (which I should have done to begin with 🙂); go ahead and close this one if you see fit.
