### ISSUE TITLE
[Bug] Folder with space in name not supported

### ISSUE THREAD

**Issue by sjiawjbssj** [FilenCloudDienste/filen-cli#197]
**Describe the bug**
I tried uploading a folder with a space in the name using this command: `upload "E:\Local Folder" /CloudFolder`
I got the error "No such source directory". After removing the space the upload worked.

**To Reproduce**
1. Create a folder with a space in the name
2. Try uploading it

**System (please complete the following information):**
- **Filen CLI version:** 0.0.17
- OS: Windows 10

**Comment by JupiterPi** [comment]
Thanks for reporting! Unfortunately, I could not reproduce this, filen-cli-v0.0.17-win-x64.exe upload "D:\Test Folder" /testfolder works fine for me. I suggest trying it in an isolated environment, or writing a more detailed step-by-step instruction to reproduce the issue.

**Comment by JupiterPi** [comment]
Should be fixed in [v0.0.22](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.22)
