### ISSUE TITLE
[Bug] CLI is suggesting to update to the older version if GitHub releases have incorrect labels for the latest

### ISSUE THREAD

**Issue by kachick** [FilenCloudDienste/filen-cli#201]
**Describe the bug**

CLI is suggesting to update to the older version if GitHub releases have incorrect labels for the latest.

**To Reproduce**

```console
> ./filen-cli-v0.0.21-linux-x64
Update from v0.0.21 to v0.0.19? [y/N]
```

**Expected behavior**

updater does not report anything if target is older or equal with current version

**Logs/Screenshots**

With current github releases

![image](https://github.com/user-attachments/assets/566ff1c3-6db8-49e1-9113-5344d53a9a13)

**System (please complete the following information):**
- **Filen CLI version:v0.0.21**
- which build of the CLI you're using: `filen-cli-v0.0.21-linux-x64`
- OS: Ubuntu

**Additional context**

**Comment by JupiterPi** [comment]
Thanks for reporting/contributing! However, we publish releases without the "latest" label when we don't want users to be prompted to update yet (but still be able to update manually). Additionally, if we were to release a version with a critical bug, we would like to be able to delete that release and have users be prompted to downgrade. Therefore, I think it's best for now to leave it as is. Users who have installed the latest version manually will have to simply reject the update/downgrade.

**Comment by kachick** [comment]
Sure!
