### ISSUE TITLE
[Bug] access last command with arrow key not working

### ISSUE THREAD

**Issue by sjiawjbssj** [FilenCloudDienste/filen-cli#205]
**Describe the bug**
I can't use arrow up to access my last command anymore.
It works fine with 0.0.17 and 0.0.19.
Edit: This is only an issue in interactive mode.

**To Reproduce**
1. run e.g. filen ls
2. arrow up
3. nothing happens

**Expected behavior**
The last used command should be shown.

**System (please complete the following information):**
- **Filen CLI version:** 0.0.21
- which build of the CLI you're using: filen-cli-v0.0.21-win-x64
- OS: Windows 10

**Comment by JupiterPi** [comment]
Thanks for reporting! Should be fixed in [v0.0.23](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.23)
