### ISSUE TITLE
Upload multiple files, directory content, recursively?

### ISSUE THREAD

**Issue by anantone** [FilenCloudDienste/filen-cli#21]
Hi, nice work on the CLI! Is there currently a way to upload multiple files with one command, including recursively through directories? 
Thanks.

**Comment by JupiterPi** [comment]
At the moment, it is only possible to upload one file at a time using the `upload` command. More complex sync operations, auch as recursive uploading of directories, will be available in the near future.

**Comment by Dwynr** [comment]
@JupiterPi Rel: [	public async uploadLocalDirectory({](https://github.com/FilenCloudDienste/filen-sdk-ts/blob/d3070588e071e2967c405168f53e29b5103d98ed/src/cloud/index.ts#L3791)
 
 `filen.cloud().uploadLocalDirectory()`

**Comment by anantone** [comment]
With the recent addition of Webdav server, one can use rclone for the same purpose.

**Comment by Ethorbit** [comment]
> At the moment, it is only possible to upload one file at a time using the `upload` command. More complex sync operations, auch as recursive uploading of directories, will be available in the near future.

Has the ability to upload multiple files been added yet? Because I cannot get it to work with my fairly large project. Sync is only creating directories, stalling permanently afterwards, and Upload is exiting immediately with errors about file names.

I am just going to zip stuff for now, this is disappointing.

**Comment by dminca** [comment]
hi, just came here to say that I noticed this was missing while attempting an upload like

```sh
upload /my-path/* filen-path/
```

then finally realized it's not supported. Would be cool to have this.

I was then trying to find if there's an `-r` argument I was missing but got no help by running `upload -h` 🤷‍♂ 

Also, bear in mind, inside the `filen-cli` context, you cannot reference local files in a relative fashion ie. `~/Path/to/file` you have  to pass the dir in absolute format `/Users/joe/Path...`
