### ISSUE TITLE
[Bug] Broken Links in Documentation

### ISSUE THREAD

**Issue by turnercore** [FilenCloudDienste/filen-cli#211]
Links in the documentation are broken, for example the link "accessing your filen drive" is going to https://docs.filen.io/docs/cli/cli/access-filen-drive

It should be going to 
https://docs.filen.io/docs/cli/access-filen-drive

Note the extra /cli in the incorrect url.

Should be an easy fix!

Cheers

![CleanShot 2024-12-01 at 14 39 31@2x](https://github.com/user-attachments/assets/6a8927ce-ebbf-4def-b78b-6006c3c56e36)
from https://docs.filen.io/docs/cli/

**Comment by KhaaL** [comment]
I can also add that `https://docs.filen.io/docs/cli/syncing` contains a broken link to `https://filen.io/apps/desktop`.

> Syncing
> (...) syncMode can be twoWay, localToCloud, localBackup, cloudToLocal or cloudBackup (see the FAQ here on what that means).

Also, the destination (the Desktop product) dosen't explain what those modes do.

**Comment by JupiterPi** [comment]
Thanks for reporting, both aspects should be fixed now.
