### ISSUE TITLE
[Bug] Sync Not Working If Write Credentials Missing

### ISSUE THREAD

**Issue by schijo** [FilenCloudDienste/filen-cli#214]
**Describe the bug**
When syncing files using Filen_linux_x86_64.AppImage (filen ui) the process ignores files which are read only. Only if write credentials are set the files are synced.

**To Reproduce**
1. Linux
2. Create file and set file credentials to r--r--r-- (touch test; chmod 444 test)
3. Create and activate sync job (mode: Local to cloud) for file or directory which includes the file
4. File is not synced
5. File is listed on "Ignored" tab

**Expected behavior**
1. File is uploaded irrespective of file credential (except read, of course)
2. In case the local file need to be deleted (modes: Two way; Cloud to local; Cloud backup) the file does not get deleted but shows up on "Ignored" or "Issues" tab

**Logs/Screenshots**
n/a

**System (please complete the following information):**
- **Filen -CLI- UI version:** 3.0.34
- Filen_linux_x86_64.AppImage
- OS: Linux (Arch Linux)

**Comment by Dwynr** [comment]
Wrong repository. This will be fixed for "localToCloud" and "localBackup" mode in the next version.
