### ISSUE TITLE
[Bug] Exclude Dot Files in CLI Sync

### ISSUE THREAD

**Issue by pablosed** [FilenCloudDienste/filen-cli#218]
Hi not really a bug, more a documentation question but am brand new to Filen and trying to setup sync using the CLI binary on my Ubuntu 22.04.5 LTS Headless server using central registry file.

I have searched the help file in the binary, reddit and the issues here and have not found a solution.

The directory in question has a lot of hidden files, that I would like to exclude from the sync. With the desktop version this seems to be trivial, however I am not seeing an obvious way to force this option in the CLI.

I have tried to include a pair in my json file like so:
```
[
{
"local": "/files/photos/2024/12/",
"remote": "/files/photos/2024/12/",
"syncMode": "localToCloud",
"excludeDotFiles": "true"
}
]
```
I have also tried a variety of options when running the command "--exclude-dot-files", "--excludedotfiles", --exclude-dotfiles"

Can you help shed some light on this. the directory and subs were created on macOS and have thousands and thousands of ._* files contained within.

Thanks

**Comment by JupiterPi** [comment]
Thanks for your feedback! I added this option in [v0.0.25](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.25).
