### ISSUE TITLE
[Bug] How to invoke Filen CLI Webdav with 2FA through docker

### ISSUE THREAD

**Issue by mvantschip** [FilenCloudDienste/filen-cli#220]
**Describe the bug**
I am uncertain how to work with the Filen CLI docker container while having 2FA enabled on my account, since the 2FA code is dynamic and thus (I assume) cannot be simply added to the CLI command in the docker-compose.yaml file.

**To Reproduce**
1. Invoke Filen CLI with arguments: '--email email --password password webdav --w-user username --w-password pass' in a Docker container, as per the README.
2. Have 2FA enabled on account.
3. The server does not start because 2FA code is required.

**Expected behavior**
A way to enter the 2FA code once and then have it authorize on subsequent docker container restarts.

**System (please complete the following information):**
- **Filen CLI version:** 0.0.24
- which build of the CLI you're using (e. g. `filen-cli-v0.0.20-linux-x64`, `filen-cli-v0.0.20-win-arm64`): docker filen/cli:latest
- OS: Ubuntu Server

**Additional context**
This is not really a bug, I am mostly looking for the ideal/secure path to take here, if that's OK. I am trying to refrain from exporting my config file, seeing that method as a last resort.

**Comment by Dwynr** [comment]
You can pass your 2FA recover key as a secure environment variable with the `--two-factor-code` command switch.
