### ISSUE TITLE
[Bug] Folder named "Windows" content is not synced to cloud

### ISSUE THREAD

**Issue by dburba** [FilenCloudDienste/filen-cli#223]
**Describe the bug**
Using docker with command sync /mnt/test:localToCloud:/test --disable-local-trash --continuous
If there is a folder named "Windows" anywhere in local path it is created in cloud, but the content is not uploaded (the folder leaves empty in the cloud)

**To Reproduce**
1. Invoke Docker Filen CLI with command: filen sync /mnt/Data:localToCloud:/Data --disable-local-trash --continuous
2. All files and folders are uploaded to cloud except named "Windows" (they are only created, but left empty)
3. No errors with --verbose, simple message, that everything is synced

**Expected behavior**
Windows folder is uploaded with all content

**System (please complete the following information):**
- **Filen CLI version:** using latest docker image, it shows:
Update available: v0.0.25 -> v0.0.24
Syncing /mnt/Data to /Data (localToCloud)...
Done syncing /mnt/Data to /Data (localToCloud)

- OS: Openmediavault 7.4.15-2  (Debian bookworm)

**Additional context**
I have 2 folders with the same name "Windows" in two different places (/mnt/Data/Software/Windows and /mnt/Data/Archive/OS/Windows) ant both of them are empty in the cloud.
All other folders and files are uploaded (did not notice something is missing yet)
If I rename folder "Windows" to something different - everything is uploaded. But after renaming back, cloud folder is renamed also and the content is deleted

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-sync/commit/f1051550674e1cd859de9c7c007b4f11022b5436
