### ISSUE TITLE
[Bug] asks for update to older version

### ISSUE THREAD

**Issue by hartmark** [FilenCloudDienste/filen-cli#228]
```
% filen-cli 
Update from v0.0.26 to v0.0.24? [y/N] 

```

**Comment by JupiterPi** [comment]
This is more or less intentional (see [#201](https://github.com/FilenCloudDienste/filen-cli/issues/201#issuecomment-2496203378)), however I'll make it clearer in the prompt.

**Comment by JupiterPi** [comment]
This is fixed with https://github.com/FilenCloudDienste/filen-cli/commit/e4baddbe13dcc338d2998a72a580f006b5f214dc
