### ISSUE TITLE
[Bug] wrong link to more details about sync options

### ISSUE THREAD

**Issue by hartmark** [FilenCloudDienste/filen-cli#232]
On this page:
https://github.com/FilenCloudDienste/filen-cli?tab=readme-ov-file#syncing

The link "here" points to a dead link:
https://filen.io/apps/desktop

But on this page:
https://github.com/FilenCloudDienste/filen-docs/blob/main/docs/cli/syncing.mdx

It points correctly to this page:
https://blog.filen.io/how-to-desktop-client/#:~:text=for%20this%20sync.-,Sync%20Modes,-%3A

**Comment by JupiterPi** [comment]
Thanks, I missed that. Should be fixed now.#
