### ISSUE TITLE
How to use 'ignore' in Syncing?

### ISSUE THREAD

**Issue by GitCourser** [FilenCloudDienste/filen-cli#234]
Using `cloudToLocal` to synchronize `cloud` to `local`, the `/media` directory of `cloud` only contains `.strm` files, while the `/root/media` directory of `local` contains not only `.strm` files but also `.nfo, .jpg...`. It is hoped that only `.strm` files will be processed during synchronization, and other files will be `ignore`, but it seems not to work, as other non-.strm files is deleted. 

syncPairs.json
```json
{
    "local": "/root/media",
    "remote": "/media",
    "syncMode": "cloudToLocal",
    "ignore": ["!*.strm"]
}
```

**Comment by Dwynr** [comment]
Should work like this:

```json
{
    "local": "/root/media",
    "remote": "/media",
    "syncMode": "cloudToLocal",
    "ignore": [
        "*",
       "!*.strm",
       "!*/"
    ]
}
```

(Ignore all files, then allow .strm extensions + directories)

**Comment by GitCourser** [comment]
thanks
