### ISSUE TITLE
Will Filen CLI get Auto Sync Feature?

### ISSUE THREAD

**Issue by iwannet** [FilenCloudDienste/filen-cli#3]
Hi,

I noticed the Filen dekstop app has an auto sync feature to automatically upload new and changed files/folders to the Filen cloud.

Are there any plans to add similar auto sync functionality to the Filen CLI as well? Having this feature in the CLI client would be very helpful and match the desktop app capabilities.

Please let me know if auto sync is on the roadmap for the Filen CLI. I'd appreciate the ability to automatically sync local folders and files to the Filen cloud.

Thank you

**Comment by JupiterPi** [comment]
Syncing is part of the roadmap for the Filen CLI. However, automatically detecting changes and syncing in the background without explicitly invoking the CLI is not planned.
