### ISSUE TITLE
Conflict between desktop app and filen-cli

### ISSUE THREAD

**Issue by zft9xgy** [FilenCloudDienste/filen-cli#37]
Hi, I already have the desktop application installed but when installing filen via brew it is not possible to install filen-cli because the app already exists. 

Although I think it was not intended for this use, it is very likely that a user has installed the desktop version and also wants to try or use filen-cli. 

```sh
~ » brew install filen                                                                                                                       
==> Downloading https://cdn.filen.io/desktop/release/filen_arm64.dmg
Already downloaded: /Users/****/Library/Caches/Homebrew/downloads/0a0d0bb257f7d7c15a26d0832227a625997b91696b34d742640836b52fd38f7b--filen_arm64.dmg
Warning: No checksum defined for cask 'filen', skipping verification.
==> Installing Cask filen
==> Purging files for version 2.0.24 of Cask filen
Error: It seems there is already an App at '/Applications/Filen.app'.
```

**Comment by JupiterPi** [comment]
`brew install filen` installs the Filen desktop client (see [here](https://formulae.brew.sh/cask/filen)). See the [README](https://github.com/FilenCloudDienste/filen-cli#installation) for information on how to install the Filen CLI.
